export const ERRORS="ERRORS";
export const GET_PRODUCTS="GET_PRODUCTS";
export const REGISTER_BEGIN="REGISTER_BEGIN";
export const REGISTER="REGISTER";
export const REGISTER_FAILED="REGISTER_FAILED";




